require("conf.run_once")
local awful = require("awful")

run_once("/home/le/bin/dock")
run_once("urxvtd","urxvtd --quiet --opendisplay --fork")
run_once("/home/le/bin/ptun")
--run_once("sudo /home/le/bin/btstart")
run_once("/home/le/bin/setxkb")
--run_once("/home/le/bin/synconfig")
--run_once("pidgin")
run_once("xbindkeys")
--run_once("hexchat")
--run_once("numlockx")
run_once("/home/le/bin/autolock")
run_once("/usr/bin/kbd_mode -u")
run_once("chromium")
run_once("blueman-applet")
run_once("nm-applet")
run_once("/home/le/bin/lock")
--run_once("sudo /home/le/bin/lighter.pl")
--run_once("/home/le/bin/swarm.sh")
--run_once("urxvtc -name systag -e bash -c \"sudo htop\"")
--run_once("urxvtc -name systag -e bash -c \"sudo powertop\"")
--run_once("urxvtc -name systag -e bash -c \"sudo i7z\"")
--run_once("urxvtc -name systag -e bash -c \"journalctl -xef\"")
