require("conf.run_once")
local awful = require("awful")

run_once("nm-applet")
run_once("/home/le/bin/xconfig")
run_once("/home/le/bin/setxkb")
run_once("/home/le/bin/synconfig")
--run_once("urxvtd","urxvtd --quiet --opendisplay --fork")
run_once("pidgin")
run_once("insync.sh")
run_once("xbindkeys")
run_once("hexchat")
run_once("numlockx")
run_once("/home/le/bin/autolock")
--run_once("/home/le/bin/skype-start")
run_once("/home/le/bin/lock")
run_once("/usr/bin/kbd_mode -u")
run_once("/home/le/bin/firefox")
run_once("/home/le/opt/Telegram/Telegram")
--run_once("/home/le/bin/webogram")
--run_once("/home/le/bin/webogram-de")

--run_once("urxvtc -name systag -e bash -c \"sudo htop\"")
--run_once("urxvtc -name systag -e bash -c \"sudo powertop\"")
--run_once("urxvtc -name systag -e bash -c \"sudo i7z\"")
--run_once("urxvtc -name systag -e bash -c \"tail -f /var/log/messages\"")
--run_once("urxvtc -name systag -e bash -c \"/home/le/bin/w\"")
